import { ExchangeRate, Expense, Goal } from "../interface/interface";

const dt = new Date();

export const balanceCards: any = [
  {
    id: "1",
    bankName: "BNC",
    gradientColors: ["#487CF3", "#011B4C"],
    balance: "1.456,65",
    currency: "VES",
    lastEntry: "01/01/2024",
    percentage: "5%",
    trendIcon: "trending-up",
  },
  {
    id: "2",
    bankName: "BANESCO",
    gradientColors: ["#00a650", "#005a2b"],
    balance: "3.120,00",
    currency: "VES",
    lastEntry: "12/02/2026",
    percentage: "12%",
    trendIcon: "trending-up",
  },
  {
    id: "3",
    bankName: "MERCANTIL",
    gradientColors: ["#1d428a", "#0d1f42"],
    balance: "850,20",
    currency: "USD",
    lastEntry: "14/02/2026",
    percentage: "2%",
    trendIcon: "trending-down",
  },
];

export const exchangeRates: ExchangeRate[] = [
  {
    exchangeName: "official",
    value: 238.84,
    todayDate: dt.toLocaleDateString(),
  },
  {
    exchangeName: "average",
    value: 286.26,
    todayDate: dt.toLocaleDateString(),
  },
  {
    exchangeName: "parallel",
    value: 333.67,
    todayDate: dt.toLocaleDateString(),
  },
];

export const goals: Goal[] = [
  {
    id: 1,
    icon: "laptop",
    title: "New Laptop",
    description: "Save money to buy a new laptop for work.",
    color: "#4CAF50",
    goalValue: 1200,
    currentValue: 1164,
    period: 6,
    periodUnit: "month",
    completed: false,
  },
  {
    id: 2,
    icon: "airplane-ticket",
    title: "Vacation Trip",
    description: "Plan and save for a vacation trip next summer.",
    color: "#2196F3",
    goalValue: 3000,
    currentValue: 3000,
    period: 12,
    periodUnit: "month",
    completed: true,
  },
  {
    id: 3,
    icon: "home",
    title: "Home Renovation",
    description: "Renovate the kitchen and living room area.",
    color: "#FF9800",
    goalValue: 5000,
    currentValue: 1000,
    period: 12,
    periodUnit: "month",
    completed: false,
  },
  {
    id: 4,
    icon: "directions-car",
    title: "New Car",
    description: "Save for a down payment on a new car.",
    color: "#9C27B0",
    goalValue: 10000,
    currentValue: 100,
    period: 12,
    periodUnit: "month",
    completed: false,
  },
  {
    id: 5,
    icon: "book",
    title: "Education Fund",
    description: "Set aside money for further education and courses.",
    color: "#E91E63",
    goalValue: 4000,
    currentValue: 2000,
    period: 12,
    periodUnit: "month",
    completed: false,
  },
];

export const constExpense: Expense[] = [
  {
    id: 1,
    icon: "laptop",
    title: "Internet",
    description: "Save money to buy a new laptop for work.",
    color: "#4CAF50",
    expenseValue: 1200,
    completed: false,
  },
  {
    id: 2,
    icon: "coffee",
    title: "Coffee",
    description: "Save money to buy a new laptop for work.",
    color: "#4CAF50",
    expenseValue: 1200,
    completed: false,
  },
  {
    id: 3,
    icon: "fast-food",
    title: "Food",
    description: "Save money to buy a new laptop for work.",
    color: "#4CAF50",
    expenseValue: 1200,
    completed: false,
  },
  {
    id: 4,
    icon: "directions-car",
    title: "New Car",
    description: "Save money to buy a new laptop for work.",
    color: "#4CAF50",
    expenseValue: 1200,
    completed: false,
  },
  {
    id: 5,
    icon: "book",
    title: "Education Fund",
    description: "Set aside money for further education and courses.",
    color: "#E91E63",
    expenseValue: 1200,
    completed: false,
  },
];
